/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package vista;

import javax.swing.JDesktopPane;
import javax.swing.JInternalFrame;

/**
 *
 * @author franco
 */
public class frmDetallePacientes extends javax.swing.JFrame {

    /**
     * Creates new form wa3
     */
    public frmDetallePacientes() {
        initComponents();
        this.setLocationRelativeTo(null);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jButton1 = new javax.swing.JButton();
        frmEditarRegistroCardiaco = new javax.swing.JButton();
        btnProgramarCita = new javax.swing.JButton();
        btnRegistrarSignos = new javax.swing.JButton();
        jLabel4 = new javax.swing.JLabel();
        jLabel1 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jButton1.setFont(new java.awt.Font("Palatino Linotype", 1, 12)); // NOI18N
        jButton1.setText("Volver menú");
        jButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton1ActionPerformed(evt);
            }
        });
        getContentPane().add(jButton1, new org.netbeans.lib.awtextra.AbsoluteConstraints(240, 230, 130, 43));

        frmEditarRegistroCardiaco.setFont(new java.awt.Font("Palatino Linotype", 1, 12)); // NOI18N
        frmEditarRegistroCardiaco.setText("Editar Informacion de signos vitales");
        frmEditarRegistroCardiaco.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                frmEditarRegistroCardiacoActionPerformed(evt);
            }
        });
        getContentPane().add(frmEditarRegistroCardiaco, new org.netbeans.lib.awtextra.AbsoluteConstraints(190, 150, -1, 30));

        btnProgramarCita.setFont(new java.awt.Font("Palatino Linotype", 1, 12)); // NOI18N
        btnProgramarCita.setText("Programar citas");
        btnProgramarCita.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnProgramarCitaActionPerformed(evt);
            }
        });
        getContentPane().add(btnProgramarCita, new org.netbeans.lib.awtextra.AbsoluteConstraints(60, 70, 170, 30));

        btnRegistrarSignos.setFont(new java.awt.Font("Palatino Linotype", 1, 12)); // NOI18N
        btnRegistrarSignos.setText("Registrar Signos Vitales");
        btnRegistrarSignos.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnRegistrarSignosActionPerformed(evt);
            }
        });
        getContentPane().add(btnRegistrarSignos, new org.netbeans.lib.awtextra.AbsoluteConstraints(370, 70, 171, 30));

        jLabel4.setFont(new java.awt.Font("Palatino Linotype", 1, 36)); // NOI18N
        jLabel4.setText("Detalles de pacientes");
        getContentPane().add(jLabel4, new org.netbeans.lib.awtextra.AbsoluteConstraints(140, 10, -1, -1));

        jLabel1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/wa/add new patient background.jpg"))); // NOI18N
        getContentPane().add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 640, 440));

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void frmEditarRegistroCardiacoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_frmEditarRegistroCardiacoActionPerformed
        // TODO add your handling code here:
        frmEditarRegistroCardiaco editar = new frmEditarRegistroCardiaco();
        editar.setLocationRelativeTo(null);
        editar.setVisible(true);
        this.dispose();
    }//GEN-LAST:event_frmEditarRegistroCardiacoActionPerformed

    private void btnProgramarCitaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnProgramarCitaActionPerformed
        // TODO add your handling code here:
        frmrPrograma cita = new frmrPrograma();
        cita.setLocationRelativeTo(null);
        cita.setVisible(true);
        this.dispose();

    }//GEN-LAST:event_btnProgramarCitaActionPerformed

    private void btnRegistrarSignosActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnRegistrarSignosActionPerformed
        // TODO add your handling code here:
        frmRegistroCardiaco cardiaco = new frmRegistroCardiaco();
        cardiaco.setLocationRelativeTo(null);
        cardiaco.setVisible(true);
        this.dispose();
    }//GEN-LAST:event_btnRegistrarSignosActionPerformed

    private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton1ActionPerformed
        // TODO add your handling code here:
        frmPrincipal principal = new frmPrincipal();
        principal.setLocationRelativeTo(null);
        principal.setVisible(true);
        this.dispose();

    }//GEN-LAST:event_jButton1ActionPerformed

    /**
     * @param args the command line arguments
     */

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnProgramarCita;
    private javax.swing.JButton btnRegistrarSignos;
    private javax.swing.JButton frmEditarRegistroCardiaco;
    private javax.swing.JButton jButton1;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel4;
    // End of variables declaration//GEN-END:variables
}
