/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package vista;

import sql.ConexionBD;
import com.sun.jdi.connect.spi.Connection;
import java.util.List;
import javax.swing.DefaultComboBoxModel;
import javax.swing.JOptionPane;
import javax.swing.table.DefaultTableModel;
import modelo.Paciente;

/**
 *
 * @author franco
 */
public class frmEditarDatos extends javax.swing.JFrame {

    private DefaultTableModel modeloTabla;

    /**
     * Creates new form wa2
     */
    public frmEditarDatos() {
        initComponents();
        this.setLocationRelativeTo(null);
        modeloTabla = new DefaultTableModel();
        tblDetalleDatos.setModel(modeloTabla);
        modeloTabla.addColumn("ID");
        modeloTabla.addColumn("Nombre");
        modeloTabla.addColumn("Edad");
        modeloTabla.addColumn("DNI");
        modeloTabla.addColumn("Teléfono");
        modeloTabla.addColumn("Dirección");
        modeloTabla.addColumn("Email");
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        btnVerDetalles = new javax.swing.JButton();
        cbxDato = new javax.swing.JComboBox<>();
        btnEditar = new javax.swing.JButton();
        btnActualizar = new javax.swing.JButton();
        btnRegistrarNew = new javax.swing.JButton();
        btnEliminar = new javax.swing.JButton();
        jLabel2 = new javax.swing.JLabel();
        txtIdBuscar = new javax.swing.JTextField();
        jLabel4 = new javax.swing.JLabel();
        txtEditarDato = new javax.swing.JTextField();
        btnBuscar = new javax.swing.JButton();
        jScrollPane1 = new javax.swing.JScrollPane();
        tblDetalleDatos = new javax.swing.JTable();
        btnVolver = new javax.swing.JButton();
        jLabel1 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        btnVerDetalles.setIcon(new javax.swing.ImageIcon(getClass().getResource("/iconos/rsz_update_details.png"))); // NOI18N
        btnVerDetalles.setText("Ver Detallles");
        btnVerDetalles.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnVerDetallesActionPerformed(evt);
            }
        });
        getContentPane().add(btnVerDetalles, new org.netbeans.lib.awtextra.AbsoluteConstraints(200, 180, -1, 50));

        cbxDato.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Item 1", "Item 2", "Item 3", "Item 4" }));
        cbxDato.setBorder(javax.swing.BorderFactory.createTitledBorder(null, "Seleccione", javax.swing.border.TitledBorder.DEFAULT_JUSTIFICATION, javax.swing.border.TitledBorder.DEFAULT_POSITION, new java.awt.Font("Palatino Linotype", 1, 12))); // NOI18N
        getContentPane().add(cbxDato, new org.netbeans.lib.awtextra.AbsoluteConstraints(280, 56, 214, 60));

        btnEditar.setIcon(new javax.swing.ImageIcon(getClass().getResource("/iconos/editar-informacion.png"))); // NOI18N
        btnEditar.setText("Editar");
        btnEditar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnEditarActionPerformed(evt);
            }
        });
        getContentPane().add(btnEditar, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 180, 100, 50));

        btnActualizar.setFont(new java.awt.Font("Palatino Linotype", 1, 12)); // NOI18N
        btnActualizar.setText("Actualizar");
        btnActualizar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnActualizarActionPerformed(evt);
            }
        });
        getContentPane().add(btnActualizar, new org.netbeans.lib.awtextra.AbsoluteConstraints(290, 460, 160, 40));

        btnRegistrarNew.setFont(new java.awt.Font("Palatino Linotype", 1, 12)); // NOI18N
        btnRegistrarNew.setIcon(new javax.swing.ImageIcon(getClass().getResource("/iconos/save-icon--1.png"))); // NOI18N
        btnRegistrarNew.setText("Registrar Nuevo Paciente");
        btnRegistrarNew.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnRegistrarNewActionPerformed(evt);
            }
        });
        getContentPane().add(btnRegistrarNew, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 460, 210, 43));

        btnEliminar.setIcon(new javax.swing.ImageIcon(getClass().getResource("/wa/Close.png"))); // NOI18N
        btnEliminar.setText("Eliminar");
        btnEliminar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnEliminarActionPerformed(evt);
            }
        });
        getContentPane().add(btnEliminar, new org.netbeans.lib.awtextra.AbsoluteConstraints(410, 180, 110, 50));

        jLabel2.setFont(new java.awt.Font("Palatino Linotype", 1, 16)); // NOI18N
        jLabel2.setText("ID");
        getContentPane().add(jLabel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(60, 70, 20, 30));

        txtIdBuscar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtIdBuscarActionPerformed(evt);
            }
        });
        getContentPane().add(txtIdBuscar, new org.netbeans.lib.awtextra.AbsoluteConstraints(90, 70, 100, 30));

        jLabel4.setFont(new java.awt.Font("Palatino Linotype", 1, 36)); // NOI18N
        jLabel4.setText("Editar datos");
        getContentPane().add(jLabel4, new org.netbeans.lib.awtextra.AbsoluteConstraints(190, 10, -1, -1));
        getContentPane().add(txtEditarDato, new org.netbeans.lib.awtextra.AbsoluteConstraints(80, 130, 420, 30));

        btnBuscar.setIcon(new javax.swing.ImageIcon(getClass().getResource("/iconos/lupa.png"))); // NOI18N
        btnBuscar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnBuscarActionPerformed(evt);
            }
        });
        getContentPane().add(btnBuscar, new org.netbeans.lib.awtextra.AbsoluteConstraints(520, 70, 60, 40));

        tblDetalleDatos.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null}
            },
            new String [] {
                "Title 1", "Title 2", "Title 3", "Title 4"
            }
        ));
        jScrollPane1.setViewportView(tblDetalleDatos);

        getContentPane().add(jScrollPane1, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 250, 530, 190));

        btnVolver.setIcon(new javax.swing.ImageIcon(getClass().getResource("/iconos/pagina-principal.png"))); // NOI18N
        btnVolver.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnVolverActionPerformed(evt);
            }
        });
        getContentPane().add(btnVolver, new org.netbeans.lib.awtextra.AbsoluteConstraints(520, 460, 40, 40));

        jLabel1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/wa/add new patient background.jpg"))); // NOI18N
        getContentPane().add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 600, 500));

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void btnEditarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnEditarActionPerformed
        // TODO add your handling code here:
        String campo = (String) cbxDato.getSelectedItem();
        String nuevoValor = txtEditarDato.getText();

        // Aquí deberías obtener el ID del paciente que se está editando
        int id = Integer.parseInt(txtIdBuscar.getText());
        Paciente paciente = new Paciente(id, null, 0, null, null, null, null); // Solo se necesita el ID para editar
        paciente.editar(campo, nuevoValor);
        JOptionPane.showMessageDialog(this, "Datos actualizados exitosamente.");
        limpiarCampos();
    }//GEN-LAST:event_btnEditarActionPerformed

    private void txtIdBuscarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtIdBuscarActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtIdBuscarActionPerformed

    private void btnBuscarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnBuscarActionPerformed
        // TODO add your handling code here:
        int id = Integer.parseInt(txtIdBuscar.getText());
        Paciente paciente = Paciente.buscarPorId(id);

        if (paciente != null) {
            JOptionPane.showMessageDialog(this, "Paciente encontrado: " + paciente.getNombre());
            // Llenar el combo box con los campos editables
            cbxDato.setModel(new DefaultComboBoxModel<>(new String[]{"nombre", "edad", "dni", "telefono", "direccion", "email"}));
        } else {
            JOptionPane.showMessageDialog(this, "Paciente no encontrado.");
        }
    }//GEN-LAST:event_btnBuscarActionPerformed

    private void btnVerDetallesActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnVerDetallesActionPerformed
        // TODO add your handling code here:
        // Limpiar la tabla antes de mostrar los detalles
        modeloTabla.setRowCount(0);

        // Obtener todos los pacientes y mostrarlos en la tabla
        List<Paciente> pacientes = Paciente.obtenerTodos();
        for (Paciente paciente : pacientes) {
            modeloTabla.addRow(new Object[]{
                paciente.getId(),
                paciente.getNombre(),
                paciente.getEdad(),
                paciente.getDni(),
                paciente.getTelefono(),
                paciente.getDireccion(),
                paciente.getEmail()
            });
        }
    }//GEN-LAST:event_btnVerDetallesActionPerformed

    private void btnActualizarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnActualizarActionPerformed
        // TODO add your handling code here:
        // Aquí puedes implementar la lógica para actualizar los datos
        for (int i = 0; i < modeloTabla.getRowCount(); i++) {
            int id = (int) modeloTabla.getValueAt(i, 0);
            String nombre = (String) modeloTabla.getValueAt(i, 1);
            int edad = (int) modeloTabla.getValueAt(i, 2);
            String dni = (String) modeloTabla.getValueAt(i, 3);
            String telefono = (String) modeloTabla.getValueAt(i, 4);
            String direccion = (String) modeloTabla.getValueAt(i, 5);
            String email = (String) modeloTabla.getValueAt(i, 6);
            // Crear un objeto Paciente y actualizarlo
            Paciente paciente = new Paciente(id, nombre, edad, dni, telefono, direccion, email);
            paciente.editar("nombre", nombre); // Actualiza el campo que desees
            // Repite para otros campos si es necesario
        }
        JOptionPane.showMessageDialog(this, "Datos actualizados exitosamente.");
        limpiarCampos();
    }//GEN-LAST:event_btnActualizarActionPerformed

    private void btnEliminarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnEliminarActionPerformed
        // TODO add your handling code here:
        try {
            String idTexto = txtIdBuscar.getText().trim();
            if (idTexto.isEmpty()) {
                JOptionPane.showMessageDialog(this,
                        "⚠️ Por favor, ingrese un ID",
                        "Campo vacío",
                        JOptionPane.WARNING_MESSAGE);
                return;
            }

            int id = Integer.parseInt(idTexto);
            Paciente paciente = Paciente.buscarPorId(id);

            if (paciente == null) {
                JOptionPane.showMessageDialog(this,
                        "❌ No se encontró paciente con ID: " + id,
                        "Paciente no encontrado",
                        JOptionPane.ERROR_MESSAGE);
                return;
            }

            // Confirmación de eliminación
            int confirmacion = JOptionPane.showConfirmDialog(
                    this,
                    "¿Está seguro de eliminar al paciente:\n"
                    + "Nombre: " + paciente.getNombre() + "\n"
                    + "ID: " + paciente.getId() + "\n\n"
                    + "⚠️ Esta acción también eliminará todos sus registros médicos asociados",
                    "Confirmar eliminación",
                    JOptionPane.YES_NO_OPTION,
                    JOptionPane.WARNING_MESSAGE);

            if (confirmacion == JOptionPane.YES_OPTION) {
                boolean eliminado = paciente.eliminar();

                if (eliminado) {
                    JOptionPane.showMessageDialog(this,
                            "✅ Paciente eliminado exitosamente",
                            "Éxito",
                            JOptionPane.INFORMATION_MESSAGE);
                    limpiarCampos();
                    btnVerDetallesActionPerformed(evt); // Actualizar tabla
                } else {
                    JOptionPane.showMessageDialog(this,
                            "❌ No se pudo eliminar el paciente",
                            "Error",
                            JOptionPane.ERROR_MESSAGE);
                }
            }
        } catch (NumberFormatException e) {
            JOptionPane.showMessageDialog(this,
                    "❌ ID inválido. Debe ser un número",
                    "Error de formato",
                    JOptionPane.ERROR_MESSAGE);
        } catch (Exception e) {
            JOptionPane.showMessageDialog(this,
                    "⚠️ Error inesperado: " + e.getMessage(),
                    "Error",
                    JOptionPane.ERROR_MESSAGE);
            e.printStackTrace();
        }
    }//GEN-LAST:event_btnEliminarActionPerformed

    private void btnRegistrarNewActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnRegistrarNewActionPerformed
        // TODO add your handling code here:
        frmRegistroPacientes registroPacientes = new frmRegistroPacientes();
        registroPacientes.setVisible(true); // Mostrar el formulario
        this.dispose(); // Cerrar el formulario actual (opcional)
    }//GEN-LAST:event_btnRegistrarNewActionPerformed

    private void btnVolverActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnVolverActionPerformed
        // TODO add your handling code here:
        frmPrincipal principal = new frmPrincipal();
        principal.setLocationRelativeTo(null);
        principal.setVisible(true);
        this.dispose();
    }//GEN-LAST:event_btnVolverActionPerformed

    private void limpiarCampos() {
        txtIdBuscar.setText("");
        txtEditarDato.setText("");
        cbxDato.setSelectedIndex(-1); // Reiniciar el combo box
    }

    /**
     * @param args the command line arguments
     */

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnActualizar;
    private javax.swing.JButton btnBuscar;
    private javax.swing.JButton btnEditar;
    private javax.swing.JButton btnEliminar;
    private javax.swing.JButton btnRegistrarNew;
    private javax.swing.JButton btnVerDetalles;
    private javax.swing.JButton btnVolver;
    private javax.swing.JComboBox<String> cbxDato;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JTable tblDetalleDatos;
    private javax.swing.JTextField txtEditarDato;
    private javax.swing.JTextField txtIdBuscar;
    // End of variables declaration//GEN-END:variables
}
