package vista;

import javax.swing.JOptionPane;

/**
 *
 * @author franco
 */
public class frmPrincipal extends javax.swing.JFrame {

    /**
     * Creates new form xdd2
     */
    public frmPrincipal() {
        initComponents();
        setTitle("Ventana Principal");
        this.setLocationRelativeTo(null);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        btnVentregistrar = new javax.swing.JButton();
        btnVentEditar = new javax.swing.JButton();
        btnVentFicha = new javax.swing.JButton();
        btnSalir = new javax.swing.JButton();
        jLabel1 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        btnVentregistrar.setIcon(new javax.swing.ImageIcon(getClass().getResource("/iconos/add new patient.png"))); // NOI18N
        btnVentregistrar.setText("Registrar Pacientes");
        btnVentregistrar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnVentregistrarActionPerformed(evt);
            }
        });
        getContentPane().add(btnVentregistrar, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 80, -1, -1));

        btnVentEditar.setIcon(new javax.swing.ImageIcon(getClass().getResource("/iconos/rsz_update_details.png"))); // NOI18N
        btnVentEditar.setText("Mostrar y editar pacientes");
        btnVentEditar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnVentEditarActionPerformed(evt);
            }
        });
        getContentPane().add(btnVentEditar, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 160, 240, 50));

        btnVentFicha.setIcon(new javax.swing.ImageIcon(getClass().getResource("/iconos/rsz_hospital_information.png"))); // NOI18N
        btnVentFicha.setText("Ficha detalla de pacientes");
        btnVentFicha.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnVentFichaActionPerformed(evt);
            }
        });
        getContentPane().add(btnVentFicha, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 220, 240, 60));

        btnSalir.setIcon(new javax.swing.ImageIcon(getClass().getResource("/iconos/exit.png"))); // NOI18N
        btnSalir.setText("Salir");
        btnSalir.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnSalirActionPerformed(evt);
            }
        });
        getContentPane().add(btnSalir, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 290, 190, 60));

        jLabel1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/wa/home.jpg"))); // NOI18N
        getContentPane().add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 960, 540));

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void btnVentregistrarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnVentregistrarActionPerformed
        // TODO add your handling code here:
        frmRegistroPacientes registro = new frmRegistroPacientes();
        registro.setLocationRelativeTo(null); // Centra la ventana
        registro.setVisible(true); // Muestra el nuevo formulario
        this.dispose(); // Cierra la ventana actual (frmPrincipal)
    }//GEN-LAST:event_btnVentregistrarActionPerformed

    private void btnVentEditarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnVentEditarActionPerformed
        // TODO add your handling code here:
        frmEditarDatos editar = new frmEditarDatos(); // Crear nueva ventana
        editar.setLocationRelativeTo(null); // Centrarla
        editar.setVisible(true); // Mostrarla
        this.dispose(); // Cerrar frmPrincipal
    }//GEN-LAST:event_btnVentEditarActionPerformed

    private void btnSalirActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnSalirActionPerformed
        // TODO add your handling code here:
        int confirm = JOptionPane.showConfirmDialog(this, "¿Estás seguro que deseas salir?", "Confirmar salida", JOptionPane.YES_NO_OPTION);
        if (confirm == JOptionPane.YES_OPTION) {
            System.exit(0);
        }
    }//GEN-LAST:event_btnSalirActionPerformed

    private void btnVentFichaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnVentFichaActionPerformed
        // TODO add your handling code here:
        frmDetallePacientes detalle = new frmDetallePacientes();
        detalle.setLocationRelativeTo(null);
        detalle.setVisible(true);
        this.dispose();
    }//GEN-LAST:event_btnVentFichaActionPerformed

    /**
     * @param args the command line arguments
     */

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnSalir;
    private javax.swing.JButton btnVentEditar;
    private javax.swing.JButton btnVentFicha;
    private javax.swing.JButton btnVentregistrar;
    private javax.swing.JLabel jLabel1;
    // End of variables declaration//GEN-END:variables
}
